# timeout
timeout = "1200s"
# your website url
baseURL = 'https://jpg.hsyam.com'
# website title
title = '.jpg'
# don't touch this
disableKinds = ["section", "taxonomy", "term", "home"]
# robots.txt
enableRobotsTXT = true

# theme as module
[module]
# replacements = "github.com/Sped0n/bridget/v2 -> ../.." # deploy with local dir (relative to hugo site theme dir)  WARN: delete this line if you want to deploy with git
[[module.imports]]
path = "github.com/byesyam/jpg.hsyam.com" # deploy with git (recommended)
